import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@lib/utils";
import { ThemeProvider } from "@components/theme/theme-provider";
import { SiteHeader } from "@components/layout/site-header";
import { SiteFooter } from "@components/layout/site-footer";
import { ScrollArea } from "@components/ui/scroll-area";
import { SidebarNav } from "@components/layout/sidebar-nav";
import { routesConfig } from "@lib/config";
import { Toaster } from "@/src/components/ui/toaster";
import { SessionProvider } from "next-auth/react";
import { auth } from "@lib/auth";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Mathwars | Makje",
  description: "Generated by create next app",
  icons: {
    icon: ["/favicon.ico?v=4"],
    apple: ["/apple-touch-icon.png?v=4"],
    shortcut: ["/apple-touch-icon.png"],
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <SessionProvider session={session}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="relative flex min-h-screen flex-col bg-background">
              <SiteHeader />
              <main className="flex-1">
                <div className="border-b">
                  <div className="container flex-1 items-start md:grid md:grid-cols-[220px_minmax(0,1fr)] md:gap-6 lg:grid-cols-[240px_minmax(0,1fr)] lg:gap-10">
                    <aside className="fixed top-14 z-30 -ml-2 hidden h-[calc(100vh-3.5rem)] w-full shrink-0 border-r md:sticky md:block">
                      <ScrollArea className="h-full py-6 pr-6 lg:py-8">
                        <SidebarNav items={routesConfig.sidebarNav} />
                      </ScrollArea>
                    </aside>
                    <div className=" min-h-screen ">{children}</div>
                  </div>
                </div>
              </main>
              <SiteFooter />
            </div>
          </ThemeProvider>
        </SessionProvider>

        <Toaster />
      </body>
    </html>
  );
}
